### ISSUE TITLE
Enable UserMenu settings to allow user menu to be customised

### ISSUE THREAD

**Issue by roelmann** [roelmann/moodle-theme_flexibase#10]
Enable UserMenu settings to allow user menu to be customised

**Comment by derekc** [comment]
There are two menu areas where this is of interest to me.

1) The UserMenu, which I believe is the dropdown near your profile here:
![64 menus](https://cloud.githubusercontent.com/assets/687780/12045790/7a1b8972-af0f-11e5-968e-cdbffe5b2d6f.png)
2) The items on the Custom Menu:
![64 menus 2](https://cloud.githubusercontent.com/assets/687780/12045793/854c67da-af0f-11e5-8915-6e493390fab8.png)

Regards, Derek

**Comment by roelmann** [comment]
https://github.com/roelmann/moodle-theme_flexibase/commit/085da658213f0eedb5297919e3d382e6c9d7035c
