### ISSUE TITLE
session_key not being passed to the course_overview block in v3.2.1b (2016082302) (Moodle 3.1)

### ISSUE THREAD

**Issue by rljesse** [roelmann/moodle-theme_flexibase#102]
We're using Moodle 3.1 with Flexibase v3.2.1b.

On a user's dashboard, if you attempt to change the value for "Number of courses to display:" from "Always show all" to any other value, it seems to not take the change. The page reloads, the URL changes to include ?mynumber=1 but the number of courses to display is still set to "Always show all" and it doesn't seem to apply the filter. 

We think that the issue may be that the user's session key is not being passed to the block. This functionality does seem to work correctly in other themes, which is why I'm posting the issue here.

**Comment by roelmann** [comment]
https://github.com/roelmann/moodle-theme_flexibase/commit/9d84045bba053e369fed91525961470c535d430e
