### ISSUE TITLE
Trashed my site again trying to do an update

### ISSUE THREAD

**Issue by derekc** [roelmann/moodle-theme_flexibase#17]
Richard, I was curious to see what the small tweaks you made were.
1) I went to master
2) downloaded zip and unzipped
3) renamed folder to theme_flexibase
4) rezipped - uploaded
5) got this:

![74 trashed](https://cloud.githubusercontent.com/assets/687780/11948051/26cf3ec6-a8d4-11e5-908d-3e08cabead20.png)

So I managed to trash the site again.  Just worse than last time.  :-)  I can't even get into it.  

While not exactly sure but two things occur to me
*How to clean this up.  Can I just delete a theme folder on the server?
*Then: what to download to get the latest zip?

(Sorry!!)

-Derek

**Comment by roelmann** [comment]
You need to rename the folder to just plain 'flexibase' not theme_flexibase
Yes you can delete what you have installed from the folder as it wont have installed properly to the database anyway, so you can just delete it - I believe from teh testing I did previously that it will have created 2 folders, one of which is actually the base theme folder renamed.
Personally, I think this renaming of zipped folders issue is probably something that the Moodle core install code should be error trapping, but it doesn't right now, so you need to ensure, if you download the zip from github that the folder inside the zip gets renamed as 'flexibase'

**Comment by roelmann** [comment]
This is not a theme issue to be fixed, but will leave the issue 'open' for a while for information for readers

**Comment by roelmann** [comment]
Closing issue as new theme version is now available from the themes database and most users will install from there or through cloning from github, rather than using the github zip file and having to rename.
