### ISSUE TITLE
xxyy appearing on page redirect

### ISSUE THREAD

**Issue by roelmann** [roelmann/moodle-theme_flexibase#18]

**Comment by roelmann** [comment]
https://github.com/roelmann/moodle-theme_flexibase/commit/8984707f17f232cca90c6c9a804d35c009070641

**Comment by roelmann** [comment]
Also appears on maintenance pages
Caused by one of the tests in modernizr,js

**Comment by derekc** [comment]
Version 3.0.6
Seems fixed maybe?

-Derek

**Comment by roelmann** [comment]
Fixed on some pages Derek, but it was still appearing on others when I tested it.
I'd like to solve the underlying issue with modernizr.js even if I have managed to hide it on some pages, so re-opened the issue for myself :)

**Comment by roelmann** [comment]
Reverse previous commit https://github.com/roelmann/moodle-theme_flexibase/commit/8984707f17f232cca90c6c9a804d35c009070641
Update modernizr.js
https://github.com/roelmann/moodle-theme_flexibase/commit/0923774ed44ad91db772d5217b035a2b52d8d8ba

**Comment by roelmann** [comment]
Believe this is now properly fixed
