### ISSUE TITLE
Reduce the number of renderers

### ISSUE THREAD

**Issue by bmbrands** [roelmann/moodle-theme_flexibase#2]
I noticed you copied the bootstrap renderers which works fine. Some of them are unchanged so you could simply remove them to prevent unneeded code duplication. If you have a bugfix please request for it to be fixed in the parent theme. Thanks :)

**Comment by roelmann** [comment]
Noted: All copied across for development purposes but will reduce them before moving to Beta. Thanks Bas

**Comment by roelmann** [comment]
Fixed: https://github.com/roelmann/theme_flexibase/commit/d9836cd6b80c753207f3a111ffdfabf824880d38
