### ISSUE TITLE
Add Gareths image upload code

### ISSUE THREAD

**Issue by roelmann** [roelmann/moodle-theme_flexibase#20]

**Comment by gjb2048** [comment]
Hi Richard,

If you pay me I'll help you :).

Kind regards,

Gareth

**Comment by roelmann** [comment]
Thanks Gareth - enhancements will be a while away now due to other commitments, but I will bear your offer in mind when I next look at it. Hopefully will look myself as a learning experience first, but will let you know if I run into trouble with it.

**Comment by gjb2048** [comment]
Thank you for getting back to me Richard, good luck :)

[image: --]
Gareth J Barnard
[image: http://]about.me/gjbarnard
http://about.me/gjbarnard

**Comment by derekc** [comment]
Again a +1 from me

-Derek

**Comment by roelmann** [comment]
https://github.com/roelmann/moodle-theme_flexibase/commit/1b76907157fb881ba275c84d0cab86e96fd7f83b

**Comment by gjb2048** [comment]
Looks good :)

**Comment by roelmann** [comment]
Thanks Gareth - very few changes needed to your excellent work. Just things like the way I call the functions, as I haven't used the 'toolbox' you have in your theme. Other than that, its basically all yours (and hopefully credited as such in the files! - If not and I've missed any credits, then I will certainly add them in as I go on)

**Comment by gjb2048** [comment]
Credit is good thank you Richard.

The toolbox thing is just really a combination of autoloading for caching and an out of global scope thing.
