### ISSUE TITLE
Calendar overflow

### ISSUE THREAD

**Issue by derekc** [roelmann/moodle-theme_flexibase#22]
Just a quick note from one of the guys I work with.
![55 calendar](https://cloud.githubusercontent.com/assets/687780/12101594/72c6b9e6-b39a-11e5-8c4b-56a434969881.png)

Calendar seems to overflow with some screen resolutions.
I can get more info if you like.

-Derek

**Comment by roelmann** [comment]
Also happens in bootstrap (at a slightly wider screen) and Clean (slightly narrower)

**Comment by roelmann** [comment]
remove padding from .block .minicalendar th, .block .minicalendar td (upstream value 2px - /theme/bootstrap/less/moodle/calendar.less)
.block .minicalendar th, .block .minicalendar td  {padding: 0px;}

**Comment by roelmann** [comment]
https://github.com/roelmann/moodle-theme_flexibase/commit/a1ad9a664878dd4bb61fce61cc42333ee340cd09
