### ISSUE TITLE
Setting at course level "Show Grades" faulting

### ISSUE THREAD

**Issue by derekc** [roelmann/moodle-theme_flexibase#24]
The information for students appears like this:

![50 grades](https://cloud.githubusercontent.com/assets/687780/12159975/36b2d044-b54c-11e5-9922-f900e63f2e5a.png)

I have the header set to 75px

I wondered if I had missed a setting for this in the Flexibase settings pages.

-Derek

**Comment by derekc** [comment]
Also, I have just noticed this (below) has a hard coded link to localhost

![48 hard coding](https://cloud.githubusercontent.com/assets/687780/12160408/a33e73f4-b550-11e5-8e0d-29a4f4447293.png)

**Comment by derekc** [comment]
Ops, Sorry, pressed wrong button.
"Close" does NOT mean shut down the tab and go somewhere else.

**Comment by roelmann** [comment]
.courseheadergradepercentage table tbody tr:last-of-type .column-itemname,
.courseheadergradepercentage table tbody tr:last-of-type .column-percentage {
font-size:120%;
}
Will bring the course link back to a single line and so should fit with a 75px header

localhost link - obviously a BUG that needs fixing asap
for now, if you want to fix yourself, then in /flexibase/layout/includes/coursegrade.php, change  Line 52
//        echo '<a href="http://localhost/moodle/grade/report/user/index.php?id='.$COURSE->id.'"';
        echo '<a href="'.$CFG->wwwroot.'/grade/report/user/index.php?id='.$COURSE->id.'"';

**Comment by roelmann** [comment]
Correct hard coded link
https://github.com/roelmann/moodle-theme_flexibase/commit/3caf0aabc058cab60de52baed800fcc8d8450693
Change language file to give detail of font-size change if small course header image used
https://github.com/roelmann/moodle-theme_flexibase/commit/ff1c4ce05890a96c49acb60f7f893fe2ac23b651

**Comment by derekc** [comment]
Thanks for this Richard.  And the other fixes.

**Comment by derekc** [comment]
We have hidden it this function.  With the fixes it made it smaller, but there is still something causing the white menu bar to increase in size.

![38 calendar icon](https://cloud.githubusercontent.com/assets/687780/12251738/0da07ace-b936-11e5-9418-8a85b69a7115.png)

**Comment by derekc** [comment]
We have hidden this information in the header. While the fixes made it smaller, there is still something causing the white menu bar to increase in size.

![38 grade in header](https://cloud.githubusercontent.com/assets/687780/12251763/32ad5a62-b936-11e5-8b08-50ea58a7a26e.png)
