### ISSUE TITLE
Misaligned categories on the front page

### ISSUE THREAD

**Issue by derekc** [roelmann/moodle-theme_flexibase#25]
Is this a setup something I have not got right:

![49 categories](https://cloud.githubusercontent.com/assets/687780/12160157/2db3afde-b54e-11e5-87a6-f552c348bb19.png)

I can see the obvious fix.  (Make all the category names the same length)
-Derek

**Comment by roelmann** [comment]
Its a side effect of the flexbox - but an unwanted one!
Options - 
1. make category names the same length
2. set a fixed height for the category tile in the theme style/customcss. The downside of that is that if someone had an even longer category name, then it may cut off.
Add the following to customcss
.flexibasecats.panel {height: 230px;}

**Comment by roelmann** [comment]
styles.php to fix category panel height at 230px (suitable for two line titles)
language file altered to explain the fixed height and how to adjust it if required.

**Comment by roelmann** [comment]
https://github.com/roelmann/moodle-theme_flexibase/commit/271a4a8ddf062d1e04665fdef7a91bce2b8444f4
