### ISSUE TITLE
Unusual stretch in tabs

### ISSUE THREAD

**Issue by derekc** [roelmann/moodle-theme_flexibase#26]
This is the tabs in the groups screen for a course.
This effect is in several other pages as well.  I can add some more screen snaps if it is useful.

![47 tabs](https://cloud.githubusercontent.com/assets/687780/12161627/d2e7cab8-b55c-11e5-88b7-f99b0eea788c.png)

-Derek

**Comment by roelmann** [comment]
While I check if this is coming from upstream bootstrap, please add
.nav-tabs.nav-justified {width: auto;}
to customcss

**Comment by roelmann** [comment]
Added to styles.css
https://github.com/roelmann/moodle-theme_flexibase/commit/a2f2155012ed70e4429c83db379abc07ba08a7f7
