### ISSUE TITLE
Feature Request: remove or hide links

### ISSUE THREAD

**Issue by derekc** [roelmann/moodle-theme_flexibase#28]
Is there an easy way to remove or hide just these two links:
![40 links to remove](https://cloud.githubusercontent.com/assets/687780/12246520/c663158a-b913-11e5-8110-16fe6d8dbe42.png)

**Comment by roelmann** [comment]
Temporary work around (there's no setting for this yet, although it is already on the enhancements list - https://github.com/roelmann/moodle-theme_flexibase/issues/3)

comment out (or delete) renderers/core_renderer.php L159-172

**Comment by roelmann** [comment]
Closed as duplicate
