### ISSUE TITLE
Editing mode on and Admin view 

### ISSUE THREAD

**Issue by derekc** [roelmann/moodle-theme_flexibase#29]
Some suggestions.

These are philosopical questions really.  One person's editing icons are another persons clutter.  The choices at home page and at course level are different.\

Firstly, have an edit on button on the home page (they exist at course level):
![39 edit button](https://cloud.githubusercontent.com/assets/687780/12246618/58e39038-b914-11e5-8608-a0247387eb14.png)
Next, Edit icon for sections and labels at course level WHEN EDITING IS ON:
![39 edit icon](https://cloud.githubusercontent.com/assets/687780/12246628/68b20c06-b914-11e5-9fcf-6fff7b911eb9.png)
They exist on the home page:
![39 front page](https://cloud.githubusercontent.com/assets/687780/12246638/747c3f5c-b914-11e5-9167-1f94643a8e20.png)

**Comment by roelmann** [comment]
I believe these are core moodle functions (ie compare to Clean and it is the same). It would need significant development to add the functionality to flexibase.
I'll look at it, but probably a long term enhancement - maybe a tracker improvement for core! :)

**Comment by derekc** [comment]
Ahh.  I'll create a tracker item.  See what happens.

-Derek
