### ISSUE TITLE
NavBar menu options

### ISSUE THREAD

**Issue by roelmann** [roelmann/moodle-theme_flexibase#3]
Create a settings page to customised the main theme navbar (My Courses, Calendar, etc)

**Comment by roelmann** [comment]
Code for this was left in the awesomebar from upstream, but was commented out as unused in flexibase - could be re-enabled?

**Comment by derekc** [comment]
OK, +1 to this, ignore my comments on the other Issue, I did not see this.
I'd personally like to get rid of icons.  But again, I can live with them.

-Derek

**Comment by roelmann** [comment]
https://github.com/roelmann/moodle-theme_flexibase/commit/085da658213f0eedb5297919e3d382e6c9d7035c
