### ISSUE TITLE
Awesomebar clash with full screen mode in ATTO with plugin

### ISSUE THREAD

**Issue by derekc** [roelmann/moodle-theme_flexibase#30]
![39 atto plugins](https://cloud.githubusercontent.com/assets/687780/12246693/d00d2ec6-b914-11e5-9a67-db8b0dd7c149.png)

**Comment by roelmann** [comment]
Is full screen an installable plugin for Atto as I don't seem to have it.
Full screen in TinyMCE removes all surrounding options including awesomebar, so this may be an issue for the Atto plugin. I'll have to find it and install it to check.
However, worth noting that no theme guarantees it will work with all non-core plugins (which doesn't mean I won't check specific ones like this on request :) )

**Comment by derekc** [comment]
Yes, it's a plugin, I should have said this: https://moodle.org/plugins/atto_fullscreen
I know: templates will not always play nicely with other plugins.

-Derek

**Comment by derekc** [comment]
OK, I will post over on the ATTO plugins page

-Derek

**Comment by derekc** [comment]
Fixed.  CSS from https://moodle.org/plugins/atto_fullscreen

.atto-fullscreen #awesomebar {
display: none;
visibility: hidden
}

From Daniel Thies

**Comment by roelmann** [comment]
Thanks Derek
Added to github
https://github.com/roelmann/moodle-theme_flexibase/commit/ab0eed35150052e44f982cc3d2c0ec6a78abb8b4
