### ISSUE TITLE
Width problem when slightly less than full screen

### ISSUE THREAD

**Issue by derekc** [roelmann/moodle-theme_flexibase#31]
![39 width](https://cloud.githubusercontent.com/assets/687780/12246715/eeda78fe-b914-11e5-9945-c13a4b6cb253.png)
This may need some more specifications to describe what is happening.  This is tabs from the one topic format.

-Derek

**Comment by roelmann** [comment]
One-Topic is contributed plugin. Will need to install it to check what's happening and compare to other themes.

**Comment by roelmann** [comment]
OneTopic is currently only officially supported upto Moodle 2.9. Will revisit this issue if and when a 3.0 version is released

**Comment by roelmann** [comment]
Will remove the wontfix label and take another look when this is available for Mdl3 - although as its a 3rd party plugin this may require external funding
