### ISSUE TITLE
Remove or move calendar icon | wastes space

### ISSUE THREAD

**Issue by derekc** [roelmann/moodle-theme_flexibase#32]
![38 calendar icon](https://cloud.githubusercontent.com/assets/687780/12247116/634c2d84-b917-11e5-8eb8-66b0a727d3bf.png)

Again, just a cosmetic comment

-Derek

**Comment by roelmann** [comment]
Add .eventlist .event .icon {display:none;} to customcss
But yes, does seem a pointless icon, so will remove in a future version

**Comment by roelmann** [comment]
.eventlist .event h3 {margin-top:0;} then improves the top spacing as well

**Comment by roelmann** [comment]
https://github.com/roelmann/moodle-theme_flexibase/commit/208093f03fdeef80e90c7bc4c273f9a0d42b728e
https://github.com/roelmann/moodle-theme_flexibase/commit/7dfbff42c753a51615912e81e9fcbe047417dacd
