### ISSUE TITLE
Navigation Request

### ISSUE THREAD

**Issue by derekc** [roelmann/moodle-theme_flexibase#33]
Highlight, make into a pill or a box - anything!!  the course name in the breadcrumbs.
To help new users

![38 course name in breadcrumbs](https://cloud.githubusercontent.com/assets/687780/12247163/9e173558-b917-11e5-8e22-e123011b3e98.png)

**Comment by roelmann** [comment]
OK, will look at the renderer to see how that can be achieved

**Comment by roelmann** [comment]
Renderer altered to add class to categories and courses. Simple style (bold) added to courses.
Design decision needed re additional styling. For now, I think that is enough - users can now add additional styling through customcss if required
https://github.com/roelmann/moodle-theme_flexibase/commit/4cd2e13a5de8ae142d3e0240d353a3148d5abf23
