### ISSUE TITLE
Three stacked choices onto one | save space

### ISSUE THREAD

**Issue by derekc** [roelmann/moodle-theme_flexibase#34]
Another cosmetic comment.  Could these go on one level?

-Derek

![38 put on one line](https://cloud.githubusercontent.com/assets/687780/12247186/b94d8d5e-b917-11e5-852e-a651c9305add.png)

**Comment by roelmann** [comment]
Will need to check where the code below comes from - but it's wrong and shouldn't be there (at least its wrong for this theme - may come from parent?)
#page-mod-forum-discuss .discussioncontrols .discussioncontrol {
    float: none;
    width: 100%;
}
#page-mod-forum-discuss .discussioncontrols .discussioncontrol {
    float: left;
    width: 33%;
}

**Comment by roelmann** [comment]
Temporary workaround - customcss
#page-mod-forum-discuss .discussioncontrols .discussioncontrol,
#page-mod-forum-discuss .discussioncontrols .discussioncontrol.movediscussion.movediscussion {width:auto; float:right;}
#page-mod-forum-discuss .discussioncontrols .discussioncontrol.movediscussion.movediscussion {margin-top:0;}

**Comment by roelmann** [comment]
https://github.com/roelmann/moodle-theme_flexibase/commit/208093f03fdeef80e90c7bc4c273f9a0d42b728e
