### ISSUE TITLE
Another space saving suggestion

### ISSUE THREAD

**Issue by derekc** [roelmann/moodle-theme_flexibase#35]
![38 save space](https://cloud.githubusercontent.com/assets/687780/12247205/cda16e10-b917-11e5-9a33-4522913e2b2f.png)
Two things on one level

-Derek

**Comment by roelmann** [comment]
Temporary workaround - CustomCSS
#page-course-index-category .categorypicker, #page-course-index-category #coursesearch {float:right;width:auto; margin:0 0 0 20px}

**Comment by roelmann** [comment]
https://github.com/roelmann/moodle-theme_flexibase/commit/208093f03fdeef80e90c7bc4c273f9a0d42b728e
