### ISSUE TITLE
Courses Page | extra space in categories | odd formatting of courses

### ISSUE THREAD

**Issue by derekc** [roelmann/moodle-theme_flexibase#37]
![99 flexi courses](https://cloud.githubusercontent.com/assets/687780/12414195/c3c2329e-bef8-11e5-9c24-c84f366a0357.jpg)

There is this large chunk of empty space, maybe related to all the images I switched off for each category.

Plus if there is a subcatagory, the formnatting of course names (at the bottom) changes to body style.

-Derek

**Comment by roelmann** [comment]
Derek, please can you tell me what images have been switched off and where and how and what other changes have been made as I cannot replicate this at the moment

**Comment by derekc** [comment]
Ah, slip of the pen.
I have:
*_Nothing displayed on the home page (no categories or courses) (in Front Page choices)
*_I have switched off "Enable category icons" http://<website>/admin/settings.php?section=theme_flexibase_categoryicon

If I then navigate to a category page I get the errors.

-Derek

**Comment by roelmann** [comment]
Bug caused by setting categorypanel size in previous issue
Resolved 
https://github.com/roelmann/moodle-theme_flexibase/commit/47e51c0bd08e21bf72aa985efa8de5316d39c1c8
