### ISSUE TITLE
Persistent removal of alerts

### ISSUE THREAD

**Issue by roelmann** [roelmann/moodle-theme_flexibase#45]

**Comment by roelmann** [comment]
Feedback from users (in work) Alert messages should not be user dismissable - they are there for a purpose

**Comment by roelmann** [comment]
Alerts have a permanently dismisable setting in the Adaptable theme, which works well. Consultations with admins of a several systems in work suggest these alerts should not be user removable. They are used for crucial messages and the fear is that users will begin to simply dismiss them without reading (comments based around how many people actually read the kind of popup messages and alerts on most websites or just click the 'dont show again')

**Comment by gjb2048** [comment]
Or.... make them like those birthday cake candles that re-light after a few seconds when you've blown them out.  So, dismiss the alert, then 10 seconds later, it comes back :)

**Comment by roelmann** [comment]
lol :)
Guess I'm trying to get my head around whether this is a good idea or not - I like the way it works in Adaptable, and I have had a request from one user to add this functionality when I first released the theme. But have talked to the original client and they don't want it and talked to some colleagues in work and they don't either. Currently the score is about 1 for persistent removal v 7 for not :)
So the options are to leave it as it is (users can close the alert for that session, but it reappears when the page is refreshed), or to add the persistent dismissal, and an option that allows the admin to prevent some alerts being permanently dismissed and also deal with any cookie implications for EU law (which I've also been asked about, but not sure whether it applies to this - haven't got that far yet)

**Comment by roelmann** [comment]
Current thinking is not to add the persistent dismissal. If someone wants it for their site I'll add it as a funded project

**Comment by gjb2048** [comment]
EU Cookie law is a nightmare - however if you keep the state on the server then not a cookie.  Other data protection laws might apply.  But this is just user decision data not personal identifying stuff which is exempt cookie wise (check) - I did the same thing many years ago when CT used cookies.

**Comment by roelmann** [comment]
Good point - thanks for that Gareth.
Might look at this again in the future, or if someone else requests it/funds it. For now, putting it on hold
