### ISSUE TITLE
Replace travis and deal with issues arising

### ISSUE THREAD

**Issue by roelmann** [roelmann/moodle-theme_flexibase#49]

**Comment by roelmann** [comment]
https://github.com/roelmann/moodle-theme_flexibase/commit/b0e9a846164c4e4f68e50277dc35bbbbd4feffa8

**Comment by roelmann** [comment]
Done

**Comment by roelmann** [comment]
Just noticed: minor change to bump version and readme file has caused a failed travis report with multiple spacing errors in multiple files.
Presumably something has changed in the test as only 2 lines of 2 files were changed in the repository, yet the travis tests show spacing errors in multiple files that passed previously.

**Comment by roelmann** [comment]
But the reported errors do not make sense and would cause the standard indenting to look terrible!
particularly if statements being backed out of the flow of indenting and brought 4-8 spaces back to the left

**Comment by gjb2048** [comment]
Hi Richard,

Looks like 'Code checker' was 'improved' yesterday.  I've spent literally hours today dealing with the complaints its making.

G

**Comment by gjb2048** [comment]
Also see: https://tracker.moodle.org/browse/CONTRIB-6143

**Comment by gjb2048** [comment]
Code Checker is EVIL it never makes sense, it just has to be obeyed.

**Comment by gjb2048** [comment]
Looks like the new 2.5.1: https://github.com/moodlehq/moodle-local_codechecker/releases

**Comment by gjb2048** [comment]
Indenting wise, it looks like it gets confused if the starting line is wrong around the point of whinge.  Therefore I just made that line sensible and flowed everything from that, i.e: https://github.com/gjb2048/moodle-theme_essential/commit/a85a228057a3e8e62b2966e4bfe09177a40a361e and https://github.com/gjb2048/moodle-theme_shoehorn/commit/d9cbbb0e3fb06d4a53489ab5853dcb51e1e4d75f

**Comment by gjb2048** [comment]
Good luck! :)

**Comment by roelmann** [comment]
Thanks Gareth - I guess so, and then we'll have to change them all back again when they realise they've messed up and their  own code fails against it :)

**Comment by roelmann** [comment]
The problem with the reflowing around where the code checker says its wrong is that it wants me to move it back 4 spaces, which will give 0 indent, the same as the div its wrapped in.
Asking for more info from the HQ developer team that made the changes
https://moodle.org/mod/forum/discuss.php?d=328076#p1319515

**Comment by roelmann** [comment]
https://tracker.moodle.org/browse/CONTRIB-6146

**Comment by roelmann** [comment]
Put changes on hold pending Eloy's findings in tracker relating to the code sniffer - there will be some changes because of more accurate code checking, but not the extent currently being reported.

**Comment by roelmann** [comment]
https://github.com/roelmann/moodle-theme_flexibase/commit/7f86735e4ac2dbddb6911e296ff9c70a345d98e6 - Some changes

**Comment by roelmann** [comment]
https://github.com/roelmann/moodle-theme_flexibase/commit/14936e71edcfa215b7a43455c733c9114bc99baa - Some changes in renderer files (navigation block renderer o/s as that has duplicate code issue as well (It IS duplicate code - direct from both new and old versions of the original renderer!)

**Comment by roelmann** [comment]
Closed thanks to several commits, but mainly thanks to Eloy's work correcting an issue with the php code sniffer used by Travis, upstream
