### ISSUE TITLE
Options to position custom menu

### ISSUE THREAD

**Issue by roelmann** [roelmann/moodle-theme_flexibase#5]
Create options to position the custom menu as part of AB or part of top menu bar

**Comment by roelmann** [comment]
https://github.com/roelmann/moodle-theme_flexibase/commit/8193e9e8ed4f9606c948cb46b50f7a0932d07523

**Comment by roelmann** [comment]
Unsure about this - have done it previously so coding the options is not a problem but design of this theme deliberately has custom menu on the main nav bar. Is there a benefit in having the menu on the AB?
If options included, would moving the menu then need the lower navbar removed as it would potentially be empty? Does that affect the balance and look of the page on screen? What can be done about that - or should it be left to the admin making this choice?
Are separate options for the custommenu and the theme menu (my courses, calendar etc) needed to add them both separately (or not) to the AB?
Length of number of items in AB becomes an issue?

**Comment by derekc** [comment]
Richard, this may have been me that suggested this originally.

I'm quite happy for things to remain as they are in Flexibase.  ie two menus, one AB and one Custom Menu.
I have tinkered with a lot of options in BCU, Pioneer, Shoehorn and Flexibase.  All with the aim of having everything neatly at the top, and having not too much space taken up with this.

According to my sensibilities, the choices you have in FB give all the functionality I can think of:
*Awesome bar (Y/N) at top
*Custom Menu
*UserMenu drop down
- with all banner/title options in between these two (ie banner (y/n), with or without course menu, or nothing)

My 2c

-Derek

**Comment by roelmann** [comment]
https://github.com/roelmann/moodle-theme_flexibase/commit/969d46e34bb3dde41506eb98bb723b43d0280168
This may need to be looked at again in order to make the top bar option collapsible on small screens if the menu is added there. Note also the AB is currently hidden on small screens - that may also have to be looked at.
For now, language strings warn that the main menu bar is the only responsive location for the main menu.
