### ISSUE TITLE
drag and drop region outlines to only appear when actually dragging a block

### ISSUE THREAD

**Issue by roelmann** [roelmann/moodle-theme_flexibase#58]
The regions inside the centre section already do this, so need to work out why they behave differently to the regions outside the main area.

**Comment by roelmann** [comment]
Hmm, seems to only be the case if something was originally in that block region when the page was opened.
If all blocks are removed from the region, then the page REFRESHED then the block region does not appear until something is being dragged

**Comment by roelmann** [comment]
When the page is originally rendered, the 'has block region xxx' variables are established, these remain in place until a page refresh, they are not altered by dragging blocks out of the region.
Hence the difference in testing with the content in the main centre region - they did not have content to drag out in the first place during the testing, rather than because of where they are.

**Comment by roelmann** [comment]
Not sure if this is something that can be fixed - at least not without significant time and resource as it would probably involve using ajax to reset the 'has block region' variables every time something is moved.
Potentially a core issue?
Further testing required to determine if this is an issue to be fixed/enhanced or one that is would require core changes in js/ajax relating to drag and drop of blocks

**Comment by gjb2048** [comment]
"place until a page refresh, they are not altered by dragging blocks out of the region" = wrong.  They do change when a block region becomes empty during d&d.

**Comment by roelmann** [comment]
hmm, then I wonder what is keeping those block regions open when the content is dragged out of them, while the regions that were empty when the page was rendered are only shown when actually dragging - including the same page after a refresh, that the side-post region I was looking at was then hidden until I started dragging, while prior to the refresh it was staying open after the content was dragged out of it :/

**Comment by roelmann** [comment]
Gareth is obviously correct - if they didn't change then the blocks wouldnt get displayed because the display:none would still be in place, so need to rethink the logic behind this and why it works the way it does

**Comment by roelmann** [comment]
ah - possibly (???) the $mainlayout which feeds from the ->known-region for side pre and side post is not getting updated, or that the css from them is not, so that its maintaining the twomainsides body class after the d&d until the page refresh.
That is a requirement of using the flexbox to allow the multiple layouts to be selected, so need to find a way around that so that the $mainlayouts and body classes gets updated

**Comment by roelmann** [comment]
Further investigation revealed a BUG where not all empty regions were being hidden in the flexibox.css style sheet :(
Now fixed https://github.com/roelmann/moodle-theme_flexibase/commit/9ac4406faec34168007ef716c44874f5589eef29

**Comment by lazydaisy** [comment]
Where is this "known region" coming from? That is not a Bootstrapbase expression?
There is a simple logic in Clean theme layouts if you need a better set up as the logic in AJAX D&D is based on that.
Every block region has a set of body classes associated with it, so until the layout reches the point that it triggers a body class of content-only will the CSS make the page work as it should.

To achieve this in a multi block layout is to work out all the possibilities of blocks used or empty in the body of the page and exclude those regions that are outside the region-main area.

**Comment by roelmann** [comment]
No its not bootstrap, or the standard Moodle logic Mary. It's related to the way I overrode the bootstrap grids and layouts with the flexbox layouts css and allowing the administrator to select a layout from a settings page.
So the code needs to be able to adapt for those changes, rather than just adjusting to what is in the config.php, and needs to know what regions are known about, not just which ones have content. The flexibase layout css doesn't use any of the bootstrap logic or grid css, although I have tried to keep as many of those classes in place because of the Ajax/Javascript issues, but still allowing the flexbox css to work on its classes.
Quite probably not all of them are necessary, and some of the code may possibly need to be rationalised/simplified, but certainly a number of them are used to determine whether the region is present or not, to add classes for the flexbox layout that didn't work the way I wanted it to when just using the 'has region' variables. I may well revisit the flexbox code for fb3.2, but unless its causing a bug right now, that's going to stay as a low priority for the minute.

**Comment by roelmann** [comment]
The big thing I guess is that there are two huge differences between flexibase and clean - 
One is the use of flexbox and completely removing all the bootstrap grid references from the layout styling
The second is using that flexbox styling to allow the admin to select a layout from a settings page, which is not possible in any other theme that I'm aware of and needs additional logic to facilitate
Obviously the additional block regions themselves can be achieved in standard bootstsrapbase/bootstrap themes like clean, but the layout changes from settings can't be (well, probably could be, but the logic to do so would be even more complex), the 'known regions' allow a couple of simple body classes to be added and therefore the flexbox rules to apply appropriately with relatively minor conditional statements in the layout files themselves.

**Comment by lazydaisy** [comment]
Sound interesting, I haven't had that much time to explore Flexibase yet, but now that you fixed the renderer I'll try and make time to delve into the coding to see how it's put together.
