### ISSUE TITLE
Problem with blocks

### ISSUE THREAD

**Issue by derekc** [roelmann/moodle-theme_flexibase#62]
Richard will know what this is.
See: https://moodle.org/mod/forum/discuss.php?d=329028#p1327247

-Derek

**Comment by roelmann** [comment]
Fixed - thank you for reporting Derek. This is now on github and will be pushed to the Moodle plugins database shortly
https://github.com/roelmann/moodle-theme_flexibase/commit/40f1123a6f0e2586f1d1ba32a9b9185cb84d48e9
