### ISSUE TITLE
update block method

### ISSUE THREAD

**Issue by roelmann** [roelmann/moodle-theme_flexibase#69]
$OUTPUT->blocks_for_region should be $OUTPUT->blocks

**Comment by gjb2048** [comment]
Would it make more sense to have a custom method $OUTPUT->lego() ? ;)

**Comment by roelmann** [comment]
blocks_for_region is only used as a function in core_renderer, the layout files all already use $OUTPUT->blocks.
Cannot locate any $OUTPUT->blocks_for_region as reported
The blocks_for_region function is a direct upstream copy from decaf re awesomebar therefore will not be changed in flexibase.

```
public function blocks_for_region($region) {
    global $USER;
    $blocks = $this->page->blocks->get_blocks_for_region($region);
    $blockcontents = theme_flexibase_block_manager::get_filtered_content($this->page->blocks, $this, $region);


public function blocks_for_region($region) {
    global $USER;
    $blockswanted = array();
    $blocks = $this->page->blocks->get_blocks_for_region($region);
    $blockcontents = theme_decaf_block_manager::get_filtered_content($this->page->blocks, $this, $region);
```
