### ISSUE TITLE
Link not working in carousel slider

### ISSUE THREAD

**Issue by cwkerns** [roelmann/moodle-theme_flexibase#74]
I am using the flexibase theme in a moodle installation (love it by the way) But the links that are set in the Carousel slider are not working. I set them, and they show on the settings, but when I save and refresh the home page, the slider shows, but when you hover over the link shows as #

**Comment by roelmann** [comment]
Can you tell me what version of FlexiBase you are using please as I cannot replicate this - although one thing (that perhaps I need to make clear in the setting description) is that it is necessary to put the whole URL link, including the http:// (or https://)

**Comment by cwkerns** [comment]
How do I determine that? I'm using moodle 2.8, and I using the complete link. The website is [http://www.mbcmidlandnc.com/moodle]

**Comment by cwkerns** [comment]
The only clickable link is the read more button, and when you hover over it, in the lower left hand corner the address pops up http://www.mbcmidlandnc.com/#

**Comment by roelmann** [comment]
If you go to http://www.mbcmidlandnc.com/moodle/admin/plugins.php?updatesonly=0&contribonly=1
Then look for Flexibase on your list of plugins, it should tell you the version you are using.
Alternatively, send me an email on oelmann.richard@gmail.com with a temporary admin account and I will take a quick look (although it will probably be in the morning now :) )

**Comment by cwkerns** [comment]
I think the version is 2015031801   v1.0.1. I set up the tempadmin and sent user name and pass word to your email address. Thanks so much.

**Comment by roelmann** [comment]
Ah - there is a bug in the carousel code! Not sure how that got past so much testing and usage over this time without being spotted!!!
If you have access to the code on the server, it is a relatively simple fix
https://github.com/roelmann/moodle-theme_flexibase/commit/ce8bade2514d85c23eb5e096d7a381349615f92f
If not, I will try to push the correction to the Moodle plugins database tomorrow - or you can download the fixed version from github directly https://github.com/roelmann/moodle-theme_flexibase/tree/STABLE_1

Hope that helps
R

**Comment by roelmann** [comment]
Ah - was fixed in v1.1.1, but that hasn't been tested for Moodle2.8, only 2.9+

**Comment by cwkerns** [comment]
Well that fixed it for me. Thanks again.

**Comment by roelmann** [comment]
Great, glad its sorted
