### ISSUE TITLE
questionary

### ISSUE THREAD

**Issue by Kritik77** [roelmann/moodle-theme_flexibase#77]
When the alumn trys to do a questionary, he gets the next message:

[MAIN CONTENT GOES HERE - 3Msk3RZf7A]

i activated the development messages and i got the following:

Notice: Trying to get property of non-object in /customers/c/3/2/seduccion-natural.com/httpd.www/cursos/theme/flexibase/layout/includes/footer.php on line 35 

I believe its a FlexiBase problem because with clean theme its shown well.

**Comment by roelmann** [comment]
Who is 'alumn' What is a 'Questionary' ?
'When the user tries to do a quiz, he gets the message' ???

**Comment by roelmann** [comment]
OK - it appears that running a quiz uses the incourse page layout but does not set a course->id
This seems like bug to me as I dont see the logic, but it can be worked around in the footer by excluding the mod-quiz-attempt page type from displaying the teacher's footer which is where this issue is arising (the detecting of a course id to determine whether the user has a given capability in that context in order to determine whether to display the teacher's footer block region.
 So L34 becomes
    if ($PAGE->pagelayout == 'course' || $PAGE->pagelayout == 'incourse' && $PAGE->pagetype !== 'mod-quiz-attempt') {

**Comment by roelmann** [comment]
Fixed as part of https://github.com/roelmann/moodle-theme_flexibase/commit/2dd6691b794b2b25e1f3cca5323491001d8df492

**Comment by Kritik77** [comment]
sorry, my english is very bad. hehe.

In english i believe its a Choice. When the teacher makes an exam to student.

My bug is shown using the option in which the student can explain with many lines of words

**Comment by roelmann** [comment]
Hmm - Dont have any problems with the choice activity, only the quiz attempts
If its not the Quiz attempt, then can you please post the URL of the page you are accessing.
Thank you

**Comment by Kritik77** [comment]
Yes, my problem is with quiz attempts, the url that show me the error is:

/mod/quiz/attempt.php?attempt=4

**Comment by roelmann** [comment]
OK, that should now be fixed on github with the fix above - if you have access to the code of the theme it is easy enough to copy and paste the line I posted earlier to replace the existing line 34 of footer.php (note - L34 NOT L35, even though 35 is the error being caught)

I have a few more things to do, that I am half way through, before I am ready to re-release to the plugins database but will do so by the beginning of next week I hope.

**Comment by Kritik77** [comment]
I got this development message in foot of web, i dont know if its some mutual thing...

Debug info: SELECT id,category FROM {course} WHERE id IS NULL
[array (
)]
Error code: invalidrecord

Stack trace: •line 1502 of /lib/dml/moodle_database.php: dml_missing_record_exception thrown
•line 1478 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()
•line 6938 of /lib/accesslib.php: call to moodle_database->get_record()
•line 35 of /theme/flexibase/layout/includes/footer.php: call to context_course::instance()
•line 46 of /theme/flexibase/layout/course.php: call to require()
•line 1028 of /lib/outputrenderers.php: call to include()
•line 958 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
•line 355 of /lib/outputrenderers.php: call to core_renderer->header()
•line 448 of /mod/quiz/renderer.php: call to plugin_renderer_base->__call()
•line 133 of /mod/quiz/attempt.php: call to mod_quiz_renderer->attempt_page()

**Comment by roelmann** [comment]
Yes its the same thing - for some reason the Quiz Attempt doesn't provide the course->id
I think that's a bug but the line I gave earlier works around it by excluding the quiz attempt from trying to find that course->id

**Comment by Kritik77** [comment]
i changed this line you said and now it seems it works fine. I will try to continue testing.

**Comment by Kritik77** [comment]
Ihave been continued testing and i found same error in more sites. when the student make a second (and maybe, i didnt tried yet) trys to any quiz, its given same error.

Exactly in this URL: /mod/quiz/summary.php?attempt=5

[MAIN CONTENT GOES HERE 

And finally, when teacher access to quiz to read the answer from the students, same error too.

Exactly in this URL: /mod/quiz/review.php?attempt=2

**Comment by roelmann** [comment]
Try the following to exclude ALL quiz pages
    if ($PAGE->pagelayout == 'course' || $PAGE->pagelayout == 'incourse' && substr($PAGE->pagetype,0,8) !== 'mod-quiz') {

**Comment by Kritik77** [comment]
Changed and all right now. more trys well, and teacher can see the answers without no more problems.
By the momment, i beleave entire process to make quiz is right now.
