### ISSUE TITLE
Paypal style

### ISSUE THREAD

**Issue by Kritik77** [roelmann/moodle-theme_flexibase#78]
When i use course summary to give a description of a course i can use some styles, like:

https://moodle.org/pluginfile.php/225/mod_forum/post/1344884/descripcion.jpg

but when i see this text, in description of course, just before to buy it, with payment button... the style is ugly, like:

https://moodle.org/pluginfile.php/225/mod_forum/post/1344884/resultado%20final.jpg

I could be very, very interesting that it could keep style, to be more appetizing and dont make reluctance to buy the course watching it with a poor style.

**Comment by roelmann** [comment]
Please can you give a link to the page with the paypal description on it and the paypal buttons etc as I do not use the Paypal enrolment plugin so cannot find that particular page.
I have just altered the renderer slightly to allow formatted text in the summary in most locations (ie not where the course tile or the tagged courses slider is in use). Checkout the change on git here and let me know if that helps?
https://github.com/roelmann/moodle-theme_flexibase/commit/05a1ad33d2a0b584cd11a75da2131612f6bc8f8c

**Comment by Kritik77** [comment]
Where i configure description is Site administration > Courses > Manage courses and categories > mycoursename edit. Description box.

The URL where student see this description is /enrol/index.php?id=5

I have just see not only paypal, If i have only manual enrolment, this is the same problem.

**Comment by roelmann** [comment]
That enrolment page should now accept the html tags with the change in the commit above - renderers/course_renderer.php L234-243
https://github.com/roelmann/moodle-theme_flexibase/commit/05a1ad33d2a0b584cd11a75da2131612f6bc8f8c

**Comment by Kritik77** [comment]
Done. For the momment its a perfect result.

Thank you very much.

are all this improves going to be included in any new versión of theme? Because im enjoying yet this improves and resolved bugs... but all FlexiBase users sure want too. Jeje.

**Comment by roelmann** [comment]
The previous issues you raised were pushed to the plugins database earlier today, this one will be included as soon as I have a few more things to put together to make it worth pushing to the database. In the meantime its available on the github master (should be added to the plugins database by early next week)

**Comment by roelmann** [comment]
Thanks for the compliments and the support, as well as the testing and bug finding :)
