### ISSUE TITLE
Recible Bin

### ISSUE THREAD

**Issue by Kritik77** [roelmann/moodle-theme_flexibase#79]
Same problem that in other older cases, now in section Course Administration > Recicle Bin shows following message:

[MAIN CONTENT GOES HERE

**Comment by roelmann** [comment]
OK - there appear to be a number of situations where an incourse page is not providing a course->id
Therefore currently 2 solutions
1. Remove the Teacher custom region entirely (comment out or delete https://github.com/roelmann/moodle-theme_flexibase/blob/master/layout/includes/footer.php#L34-47)
2. Make the teacher block only available on main course pages by changing https://github.com/roelmann/moodle-theme_flexibase/blob/master/layout/includes/footer.php#L34 to be
if ($PAGE->pagelayout == 'course') {

**Comment by roelmann** [comment]
Solution 1 used
