### ISSUE TITLE
Categories view

### ISSUE THREAD

**Issue by Kritik77** [roelmann/moodle-theme_flexibase#80]
When i see a category and his description, i can see in upper position, at right position, a combo box witch i can select other categories here.

I can see a problema, or a improvement here.

Description text in this screen have width reduced from left side, to the right in the point where this combo box begin.

After description i can see a search box with button to the right, and later all courses in this category. This list of courses is shown correctly, and search box is located at same point that combo box in upper section.

I can see this problema in this URL: /course/index.php?categoryid=N (Where N=Id of my category, and this error or improvement is common in all my categories.

**Comment by roelmann** [comment]
![screenshot from 2016-06-23 11 50 45](https://cloud.githubusercontent.com/assets/1045679/16300625/ca46ad74-3938-11e6-8925-5a0b8b2a93b9.png)
That space is supposed to be for the course image (see attached screenshot). If you have a course image and its not showing, then that is a bug I need to fix as it is working on my site, but I'm not on my dev site right now, so there may be some customisations on the site I just checked out. I'll look at it as soon as I get chance

**Comment by Kritik77** [comment]
i mean this examples. Not in course description like your photo, i mean in category description like this example:

![fallo1](https://cloud.githubusercontent.com/assets/19737494/16301225/89d93d4a-3944-11e6-83b2-67e64006ddea.jpg)

and more down, when category description is finished, all course`s category is shown......

![fallo2](https://cloud.githubusercontent.com/assets/19737494/16301226/89e2bd5c-3944-11e6-8f72-58af51d010e7.jpg)

**Comment by roelmann** [comment]
Add
#page-course-index-category .generalbox.info {clear: both;}
To your customcss setting :)

**Comment by Kritik77** [comment]
it doesn`t work.

Edit:
Its ok now.
A noob question: Why if i use a comment line begining with "//" this line doesnt work? Finally, i used a comment between /\* and */... but... why "//" doesnt run to use only 1 line to comment?

**Comment by roelmann** [comment]
Um - do you mean why doesn't a comment line work in the css?
Or do you mean why doesn't // work as a comment line?
CSS doesn't use that single line comment syntax for single lines, it uses it to comment the next rule/selector
http://www.xanthir.com/b4U10

**Comment by roelmann** [comment]
Added to styles css sheet
