### ISSUE TITLE
Slide title

### ISSUE THREAD

**Issue by fmeneuhe** [roelmann/moodle-theme_flexibase#83]
Hi,
Is possible to change the style of the slides title?

**Comment by roelmann** [comment]
Firebug and Chrome Developer tools are your friend for changing styles if there is no theme setting - they help you find the correct selector and try out styles before committing them to the customcss setting.
In this case it should be something like:
.carousel.slide h1 {your-styles:here;}

**Comment by fmeneuhe** [comment]
Thanks
