### ISSUE TITLE
What is "Page Block" button for?

### ISSUE THREAD

**Issue by fmeneuhe** [roelmann/moodle-theme_flexibase#88]
On the main page of the site I have a "Page Block" button.
What is this button for?
The button is not translated by moodle, so I  guess the is a custom buttom from the theme.

**Comment by roelmann** [comment]
The Page Blocks button gives a modal page of additional block regions. This allows content creators to move towards a 'block free' content page if desired (I don't but some people seem to be very vocally advocating such an approach) by moving all blocks onto this modal page.

**Comment by fmeneuhe** [comment]
Ok right. And thanks for this great theme.
