### ISSUE TITLE
Hide topic does not work

### ISSUE THREAD

**Issue by fmeneuhe** [roelmann/moodle-theme_flexibase#89]
I have found and important and blocking bug.
Inside a course, I hide a topic from the right "Edit" topic link. When I try to show the topic again, when I click on the "Edit" link I cannot select the options.
Is this a theme bug? It works with other themes.
I have tested it with latest versions of Firefox, Opera and Chrome on Windows 10.

**Comment by roelmann** [comment]
Suspect this may be a 'bug'/design change from the parent as I hadn't come across it before, but came across it in another them last week. It appears the 'hidden topic' is actually being greyed out by giving it an opacity, while if that opacity is reset to 1, it resolves the issue.
I'm away for a few days, so can't provide the actual code until the weekend, but you could try adding something like
.course-content ul li.section.hidden {
    background-color: #f2f2f2;
    opacity: 1;
}
into your custom css.
The opacity change reverses the opacity and fixes the issue with the menu, but means that the section cannot be distinguished in editing mode, so the background colour provides that 'signal'. You could use firebug to analyse other selectors within that to adjust, but that is the quick fix until I get time to look at it properly next week.

**Comment by roelmann** [comment]
Logically the opacity shouldn't be preventing the click - but when I tested it on the other theme, reverting the opacity to 1 worked.
I probably need to investigate deeper to make sure that is the actual cause, but try it as a temporary work around.

**Comment by fmeneuhe** [comment]
As a temporary workaround it works.

**Comment by roglos** [comment]
Probably a better solution (courtesy of Mary Evans on the forums)
.editing .course-content ul li.section.hidden:hover {
    background-color: #f2f2f2;
    opacity: 1;
}
Applies the css only when editing and only when hovering over that section, therefore leaves the opacity function to provide the 'hidden' distinction otherwise.

**Comment by fmeneuhe** [comment]
Much better this one thx.
