### ISSUE TITLE
Error when forcing a password change.

### ISSUE THREAD

**Issue by derekc** [roelmann/moodle-theme_flexibase#91]
Moodle: 3.0.1+ (Build: 20151231)
Flexibase: v3.2.0e 2016062200

See the comment here: https://moodle.org/mod/forum/discuss.php?d=328965

I actually can't believe this is a bug, since it has been around for a while and someone must have experienced it.

Here is the current error message:

![91](https://cloud.githubusercontent.com/assets/687780/18737090/9ed6aca2-80e1-11e6-92c1-10a3ea2b5ee5.jpg)

-Derek

**Comment by derekc** [comment]
Well, this from Decaf: https://github.com/CTANZ/moodle-theme_decaf/issues/26

-Derek

**Comment by roglos** [comment]
Thanks Derek - in Flexibase its https://github.com/roelmann/moodle-theme_flexibase/blob/master/layout/includes/awesomebarinc.php#L40 to make the same change

**Comment by roelmann** [comment]
Fixed
