### ISSUE TITLE
Small deprecated string error

### ISSUE THREAD

**Issue by derekc** [roelmann/moodle-theme_flexibase#92]
Tiny bit of code comes up deprecated:

![22 code](https://cloud.githubusercontent.com/assets/687780/18823992/7756ec36-841b-11e6-883d-6e4c04e34c27.png)

**Comment by roelmann** [comment]
I think that string is being called by block_course_menu, Derek. Flexibase
shows up in the stack trace because that's where the block region that
holds the course menu block is being called from, rather than because
that's where the string is.

**Comment by roelmann** [comment]
From the image above - L610 of /blocks/course_menu/block_course_menu.php: call to get_string()

**Comment by roelmann** [comment]
Not a Flexibase issue
