### ISSUE TITLE
Unusual styling on front page | two things

### ISSUE THREAD

**Issue by derekc** [roelmann/moodle-theme_flexibase#93]
![21 home page](https://cloud.githubusercontent.com/assets/687780/18824070/e60e1636-841b-11e6-8821-b92d9668c598.png)

Just installed new 3.2.1 on our dev site.

**Comment by roelmann** [comment]
For the login button - this appears to have the containing div applied as a button and also the <input>
To remove the outer styling add teh following to your customcss - I will add it to a fix on FB as soon as I can
**.c1.btn, .c1.btn:hover {background-image:none;background-color:transparent;border:none;padding:0}**

Now pushed to github

**Comment by roelmann** [comment]
I'm not seeing the pale green background anywhere, Derek. Can you tell me more about it? Is it on the frontpage, which part of the page?? Can you track it down using firebug or chrome developer tools?

**Comment by roelmann** [comment]
Derek, Just logged into your site - the pale green is coming from your Main Brand Colours setting for 'White' where you have put #E6FEFA
If you want to keep that setting bu override it for #region-main, then add
#region-main{background-color:#fff;}
to your customcss setting, to override the theme use of the LESS @white variable.
