### ISSUE TITLE
Popovers not working

### ISSUE THREAD

**Issue by englisheffects** [roelmann/moodle-theme_flexibase#99]
Hello! I am trying to use the popover feature from bootstrap (http://getbootstrap.com/javascript/#popovers), but it doesn't seem to work. I tried placing different variations of the javascript you see below but the popup doesn't show. Could you offer any tips? 

`$(function () {
  $('[data-toggle="popover"]').popover()
})`

**Comment by roelmann** [comment]
Appears not to work in the parent Bootstrap theme either - will investigate
